### ISSUE TITLE
an example of calling `getImage`?

### ISSUE THREAD

**Issue by aver-ua** [bitstuffing/cloudedge#1]
hi. 
@bitstuffing, thanks a lot for your work. 
can you provide an example of calling `getImage`?

**Comment by bitstuffing** [comment]
Hi, sorry about the delayed response, but this project is not supported by community people or maintained by other developers or me. I don't have this cameras anymore and nobody investigate this line so... it's difficult to support (at least for me); all was developed without any documentation or open API, just reverse-engineering.

My repository was an investigation, and I didn't reach the final goal (get it working on a PC with all cameras and information in native Linux). But... I reached get camera alerts and image miniature of this elements.  

I don't remember exactly, you can try, but you have to make:
```
from cloudedge import Cloudedge
cloudedge = Cloudedge()
# take a look the json response from login call
cloudedge.login('email@domain','password')
# see the json in screen at extract alerts, you need to get the camera identifiers, the imageUrl and the messageId
cloudedge.hasMessages()
# if there was messages continue
cloudedge.getAlertList()
# this was the mandatory, it will take you all commands
cloudedge.getImage(imageUrl, "20240101", "key-from-login-response", "signature-from-alert-list","token-from-login")
```

Sorry for that, it's an uncomplete answer but is based on my unfinished work of two years before, and I don't have time to get reverse-engineering again from cloudedge apk and re-investigate without community support in this project.

Thanks for your understanding.

Greetings
